### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by AsmaGargouri** [kuflink/angular2-mapbox#19]
I got an error when I tried to npm install the package. Is there something I should do ?

**Comment by michaelpwilson** [comment]
What is the error outputted?

**Comment by AsmaGargouri** [comment]
output of the error ; 
`npm ERR! git clone --template=C:\Users\Temp\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:mapbox/mapbox-gl-function.git C:\Users\Temp\AppData\Roaming\npm-cache\_git-remotes\git-github-com-mapbox-mapbox-gl-function-git-41c6724e2bbd7bd1eb5991451bbf118b7d02b525-c8e55334: undefined
npm ERR! git clone --template=C:\Users\Temp\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:mapbox/mapbox-gl-function.git C:\Users\Temp\AppData\Roaming\npm-cache\_git-remotes\git-github-com-mapbox-mapbox-gl-function-git-41c6724e2bbd7bd1eb5991451bbf118b7d02b525-c8e55334: undefined`

**Comment by michaelpwilson** [comment]
This isn't going to be a problem with this package, its more a problem with npm for some reason or another.

I found an issue which this error seems to point to over at npm: https://github.com/npm/npm/issues/10559
