### ISSUE TITLE
Can't import MapBoxModule

### ISSUE THREAD

**Issue by HoplaGeiss** [kuflink/angular2-mapbox#36]
When I am trying to import MapBoxModule like so:
```
import { MapBoxModule } from 'angular2-mapbox/core';
```

I am getting `Cannot read property 'getSourceFile' of undefined`

**Comment by mitulgolakiya** [comment]
@HoplaGeiss any solution on this?

**Comment by HoplaGeiss** [comment]
I gave up using this library... I think it is still too early stage to be used :)
